### ISSUE TITLE
Incorrect plane viewer tile index values

### ISSUE THREAD

**Issue by Brainulator9** [Clownacy/clownmdemu-frontend#2]
Something seems to be wrong with the plane viewer in that tile indexes do not present the correct values:

![image](https://github.com/Clownacy/clownmdemu-frontend/assets/44907795/47c98697-1e30-4831-85b8-a3640e3ef9ca)

The "A" I highlighted should be described as tile 1681/0x691, palette line 2, but is described as tile 0/0x0, palette line 0. It's not just that they're blank; I've also noticed instances elsewhere in which the X-flip, Y-flip, and priority bits are also misreported.

**Comment by Clownacy** [comment]
Thanks for catching that: it was caused by a refactor gone wrong.

**Comment by Brainulator9** [comment]
> Thanks for catching that: it was caused by a refactor gone wrong.

You're welcome. I take it, based on looking at the version history, that this refactor is you [converting VRAM from 16-bit to 8-bit](https://clownacy.wordpress.com/2023/03/01/clownmdemu-frontend-v0-4-libretro-v0-2/).

**Comment by Clownacy** [comment]
That's the one. In hindsight, I can think of a better way to do it that would less error-prone, so I should really revisit that change.
