### ISSUE TITLE
Sprites Window isn't resized correctly under latest build

### ISSUE THREAD

**Issue by DeltaWooloo** [Clownacy/clownmdemu-frontend#23]
Seems like I am unable to resize the sprites window and is resized to be a tiny window in the latest build. 

![Screenshot 2024-12-06 121829](https://github.com/user-attachments/assets/f8aeac74-c2e7-4f54-868b-eec7f52b80ae)

This is odd as in the previous build, it worked just fine. For context:
![Screenshot 2024-12-06 121954](https://github.com/user-attachments/assets/42b1f9f2-e023-47bb-b591-c286e8e43077)

I did download the latest build again and the same issues persist.

**Comment by Clownacy** [comment]
Fixed in b9f48d8da6fa02e18c5629ae39f102fee2db011e. An update should be out shortly.
