### ISSUE TITLE
Palettes do not match with Megadrive palettes

### ISSUE THREAD

**Issue by GuesterReal** [Clownacy/clownmdemu-frontend#3]
When compared to a pixeled screenshot from a Megadrive, clownmdemu is brighter

**Comment by Clownacy** [comment]
How are you comparing the two? The Mega Drive outputs an analogue signal through a video cable that's meant to be plugged straight into a CRT, while my emulator outputs a typical digital framebuffer - capturing that analogue signal through a capture card for comparison could be introducing all kinds of distortion.

**Comment by GuesterReal** [comment]
> How are you comparing the two? The Mega Drive outputs an analogue signal through a video cable that's meant to be plugged straight into a CRT, while my emulator outputs a typical digital framebuffer - capturing that analogue signal for comparison through a capture card could be introducing all kinds of distortion.

What i meant is there are emulators that match the palette on the Megadrive like Kega Fusion

**Comment by Clownacy** [comment]
That begs the same question: how do you know that Kega is accurate to a real Mega Drive?

**Comment by GuesterReal** [comment]
> That begs the same question: how do you know that Kega is accurate to a real Mega Drive?

for example when i import a sprite ripped from kega to flex2 when i have the same palette of the sprite loaded from flex2 it detects the colors no problem but when i do the same with clownmdemu it cannot detect any colors so it tries to automatically fill it in and it often fails to fully make the sprite again according to the palette loaded in flex2 also when i color inspect the colors from clownmdemu in an art tool the rgb is not the power of 2 its multiplied by 17

**Comment by Clownacy** [comment]
Kega and Flex2 must both be turning the RGB values from 3-bit (Mega Drive) to 8-bit (PC) by adding a bunch of 0 bits to the end. The problem with doing this is that 7, the maximum 3-bit value, becomes 224, which is not the maximum 8-bit value. This results in white being grey, and every colour being darker than it should be. My emulator solves this by instead turning 3-bit into 8-bit by repeating the 3-bit value. So 5 (which is 101 in binary) becomes 182 (which is 10110110 in binary) instead of 160 (which is 10100000 in binary).

**Comment by GuesterReal** [comment]
> Kega and Flex2 must both be turning the RGB values from 3-bit (Mega Drive) to 8-bit (PC) by adding a bunch of 0 bits to the end. The problem with doing this is that 7, the maximum 3-bit value, becomes 224, which is not the maximum 8-bit value. This results in white being grey, and every colour being darker than it should be. My emulator solves this by instead turning 3-bit into 8-bit by repeating the 3-bit value. So, for example, 5 (which is 101 in binary) becomes 182 (which is 10110110 in binary) instead of 160 (which is 10100000 in binary). This way, 7 becomes 255.

though how can i import a sprite to a sprite editor when i rip one from clownmdemu?

**Comment by Clownacy** [comment]
It would be nice if Flex2 let you specify a colour encoding when importing...

Assuming you're using an advanced image editor like GIMP, you can convert the image to indexed and then edit each colour in the palette. Dividing the RGB values of each colour by 32 and then multiplying them by 32 should make the colour compatible with Flex2. Once all colours are edited, then you can import the image into Flex2.

**Comment by GuesterReal** [comment]
can i do that in pixel art tools like web version pixilart?

**Comment by Clownacy** [comment]
I think so?

**Comment by GuesterReal** [comment]
and what do you mean by indexed? Thats why i asked the pixel art tool thing

**Comment by Clownacy** [comment]
An image is indexed when it uses a colour palette, instead of each pixel being its own colour. If the image uses few different colours, then editing a palette is faster than editing the colour of each pixel.

**Comment by GuesterReal** [comment]
sure thanks for the info, so shall i close this issue?

**Comment by Clownacy** [comment]
Sure.
