### ISSUE TITLE
Working directories are spammed with configuration files

### ISSUE THREAD

**Issue by vladikcomper** [Clownacy/clownmdemu-frontend#4]
Clownmdemu-frontend currently stores and loads configuration files in the current working directory instead of a sane shared path (e.g. `%AppData%\Clownmdemu` on Windows or `~/.config/Clownmdemu` on Linux or just the directory it was compiled in).

If you add `clownmdemu-frontend` to `PATH` on either OS and invoke it from CLI like so ...
```sh
clownmdemu-frontend rom.bin
```
... it leads to a few side effects:

1. `clownmdemu-frontend` spams every working directory with 2 .ini files:
   - `clownmdemu-frontend.ini`
   - `clownmdemu-frontend-imgui.ini`
2. Configuration files are re-created every time, which means they aren't persistent and don't have a single source of truth.

It took me a few invocations of Clownmdemu from various directories to get my entire work tree spammed like so:

![Screenshot_20240217_175718](https://github.com/Clownacy/clownmdemu-frontend/assets/18137266/223af78d-f502-46aa-abae-6c2f7b944e0d)

This is the reason most of the programs store configuration files in a shared directory instead of the current working one.

**Comment by Clownacy** [comment]
Fixed in 6f7a73d1c01bac551090445141f6305be25f2426.
