### ISSUE TITLE
First frame going backwards is forwards

### ISSUE THREAD

**Issue by Brainulator9** [Clownacy/clownmdemu-frontend#7]
It seems that the first frame in which you hold (or let go of) the reverse button still goes forward, and the first frame in which you let go of the reverse button still goes backwards. This is best observed with the frame-advance function, though I think it happens regardless of whether you pause emulation or not.

**Comment by Clownacy** [comment]
Fixed in 22db2edbcc374565347fd17fe3f4986be799cc57 and a215d5af29e42cce35e61aa28b509fb8c799facf.
